# Generated by Django 3.0.6 on 2020-05-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, help_text='Current board member')),
                ('date_time_added', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the title of the organization or department', max_length=255, unique=True)),
                ('history', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, upload_to='Users_image')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='DB.Person')),
                ('residency', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(blank=True, default='+254', max_length=25)),
                ('occupation', models.CharField(blank=True, max_length=250)),
                ('citizenship', models.CharField(blank=True, max_length=150)),
                ('marital_status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
            ],
            bases=('DB.person',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Switch to activate this settings as the Organizations Current Settings...NB\nThis will Affect All The Systems Setting')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Organization_images')),
                ('phone_number', models.CharField(help_text='Official Organizations PhoneNumber', max_length=25)),
                ('email', models.EmailField(help_text='Official Organizations email', max_length=254)),
                ('logo', models.ImageField(upload_to='Organization_images')),
                ('board_members', models.ManyToManyField(help_text='Add board members', to='DB.BoardMember')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.OrganizationHistory')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.ChurchMember')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('department_head', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='head_of_department', to='DB.ChurchMember')),
                ('department_secretary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secretary', to='DB.ChurchMember')),
                ('department_treasurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='department_treasurer', to='DB.ChurchMember')),
                ('members_of_department', models.ManyToManyField(blank=True, related_name='members_of_department', to='DB.ChurchMember')),
            ],
        ),
        migrations.AddField(
            model_name='boardmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.ChurchMember'),
        ),
    ]
