# Generated by Django 3.0.6 on 2020-06-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_auto_20200528_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrganizationHistory',
        ),
    ]
