# Generated by Django 3.0.6 on 2020-05-24 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchDevelopment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contribution_type', models.CharField(choices=[('General Contribution', 'General Contribution'), ('Member Contribution', 'Member Contribution')], max_length=20)),
                ('target_amount', models.IntegerField()),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contribution.Contribution')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchDevelopmentContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('comment', models.CharField(blank=True, help_text='Any comments', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contribution.ChurchDevelopment')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.ChurchMember')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchContribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contribution_date', models.DateField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('slug', models.SlugField(blank=True)),
                ('recorded_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Contribution.Contribution')),
            ],
        ),
    ]
