# Generated by Django 3.0.6 on 2020-05-24 16:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Contribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
