# Generated by Django 3.0.6 on 2020-06-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contribution', '0002_contribution_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
