# Generated by Django 3.0.6 on 2020-05-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('Head', 'Head'), ('Secretary', 'Secretary'), ('Treasurer', 'Treasurer')], max_length=10)),
                ('group', models.ForeignKey(help_text='If Left Blank User Will Get System Wide Access', on_delete=django.db.models.deletion.CASCADE, to='DB.Department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.ChurchMember')),
            ],
        ),
    ]
