# Generated by Django 3.0.6 on 2020-05-28 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
        ('Configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='group',
            field=models.ForeignKey(blank=True, help_text='If Left Blank User Will Get System Wide Access', null=True, on_delete=django.db.models.deletion.CASCADE, to='DB.Department'),
        ),
    ]
