# Generated by Django 3.0.6 on 2020-05-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0002_auto_20200528_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemuser',
            old_name='user',
            new_name='member',
        ),
    ]
