# Generated by Django 3.0.6 on 2020-06-01 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_auto_20200601_1044'),
        ('Configuration', '0004_auto_20200528_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the title of the organization or department', max_length=255, unique=True)),
                ('history', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, help_text='Switch to activate this settings as the Organizations Current Settings...NB\nThis will Affect All The Systems Setting')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='Organization_images')),
                ('phone_number', models.CharField(help_text='Official Organizations PhoneNumber', max_length=25)),
                ('email', models.EmailField(help_text='Official Organizations email', max_length=254)),
                ('logo', models.ImageField(upload_to='Organization_images')),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Configuration.OrganizationHistory')),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.ChurchMember')),
            ],
        ),
    ]
