# Generated by Django 3.0.6 on 2020-06-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Configuration', '0007_auto_20200601_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact',
            field=models.CharField(blank=True, help_text='Official Organizations PhoneNumber', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, help_text='Official Organizations email', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Organization_images'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='Organization_images'),
        ),
    ]
